In [240]:
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree
modelTree = tree.DecisionTreeClassifier()
from sklearn.naive_bayes import MultinomialNB
modelNB = MultinomialNB()
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import confusion_matrix, classification_report
# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import pandas as pd

In [241]:
df = pd.read_csv("dataset.csv")

In [242]:
df.head()

id  encode diagnosis  radius_mean  texture_mean  perimeter_mean  \
0    842302       1         M        17.99         10.38          122.80   
1    842517       1         M        20.57         17.77          132.90   
2  84300903       1         M        19.69         21.25          130.00   
3  84348301       1         M        11.42         20.38           77.58   
4  84358402       1         M        20.29         14.34          135.10   

   area_mean  smoothness_mean  compactness_mean  concavity_mean  ...  \
0     1001.0          0.11840           0.27760          0.3001  ...   
1     1326.0          0.08474           0.07864          0.0869  ...   
2     1203.0          0.10960           0.15990          0.1974  ...   
3      386.1          0.14250           0.28390          0.2414  ...   
4     1297.0          0.10030           0.13280          0.1980  ...   

   radius_worst  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0         25.38          17.33           184.60      2019.0            0.1622   
1         24.99          23.41           158.80      1956.0            0.1238   
2         23.57          25.53           152.50      1709.0            0.1444   
3         14.91          26.50            98.87       567.7            0.2098   
4         22.54          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 33 columns]

In [243]:
inputs = df.drop(['id','diagnosis','encode'],axis='columns')

In [244]:
target = df['encode']

In [245]:
inputs

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [246]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [247]:
modelNB = MultinomialNB()
modelNB.fit(X_train,y_train)
modelNB.score(X_train, y_train)

0.907035175879397

In [248]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [249]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)

svm.score(X_train, y_train)
#print(pred)
pred = svm.predict(X_test)
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.98       107
           1       0.95      0.97      0.96        64

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171

[[104   3]
 [  2  62]]


In [250]:
modelTree.fit(X_train, y_train)
modelTree.score(X_train, y_train)
pred = modelTree.predict(X_test)
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

           0       0.93      0.90      0.91       107
           1       0.84      0.89      0.86        64

    accuracy                           0.89       171
   macro avg       0.89      0.89      0.89       171
weighted avg       0.90      0.89      0.90       171

[[96 11]
 [ 7 57]]


In [251]:
mlp = MLPClassifier(hidden_layer_sizes=(10,10,10), activation='relu', solver='adam', max_iter=1500)
mlp.fit(X_train,y_train)
print(mlp.score(X_train,y_train))
#pred_mlpc = mlp.predict(y_train)
pred = mlp.predict(X_test)
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

0.9974874371859297
              precision    recall  f1-score   support

           0       0.98      0.97      0.98       107
           1       0.95      0.97      0.96        64

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171

[[104   3]
 [  2  62]]


In [282]:
from sklearn.model_selection import cross_val_score

In [283]:
print(cross_val_score(SVC(gamma='auto'),inputs,target, cv=10))

[0.62068966 0.62068966 0.63157895 0.63157895 0.63157895 0.63157895
 0.63157895 0.625      0.625      0.625     ]


In [284]:
print(cross_val_score(MLPClassifier(hidden_layer_sizes=(10,10,10), activation='relu', solver='adam', max_iter=1500),inputs,target,cv=10))

[0.9137931  0.9137931  0.92982456 0.94736842 0.92982456 0.89473684
 0.98245614 0.92857143 0.89285714 0.94642857]


In [285]:
print(cross_val_score(MultinomialNB(),inputs,target,cv=10))

[0.86206897 0.87931034 0.87719298 0.92982456 0.87719298 0.87719298
 0.9122807  0.92857143 0.89285714 0.89285714]


In [286]:
print(cross_val_score(modelTree,inputs,target,cv=10))

[0.89655172 0.86206897 0.9122807  0.87719298 0.92982456 0.9122807
 0.87719298 0.94642857 0.91071429 0.96428571]
